name: Running
description: Running
inputs:
  work-dir:
    description: Path where build should be done
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Running index.js
      run: |
        node index.js
      shell: bash
      working-directory: ${{ inputs.work-dir }}
