name: Running
description: Running
# inputs:
#   work-dir:
#     description: Path where build should be done
#     required: true
#   name:
#     description: Name to hello
#     required: true

outputs:
  aaa:
    description: asd
    value: ${{ steps.aaa.outputs.name }}
runs:
  using: "composite"
  steps:
    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: "18"

    - name: Running index.js
      id: aaa
      run: ${{ github.workspace }}/.github/actions/run-code/run-code.sh
      shell: bash
