name: Running
description: Running
# inputs:
#   files:
#     description: Path where build should be done
#     required: true
#   name:
#     description: Name to hello
#     required: true
outputs:
  path:
    description: path
    value: ${{ steps.script.outputs.path }}
  name:
    description: name
    value: ${{ steps.script.outputs.name }}

runs:
  using: "composite"
  steps:
    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: "18"

    - name: Running index.js
      id: script
      run: ${{ github.workspace }}/.github/actions/run-code/run-code.sh >> $GITHUB_OUTPUT
      shell: bash
