name: Running
description: Running
inputs:
  files:
    description: Path where build should be done
    required: true
#   name:
#     description: Name to hello
#     required: true

runs:
  using: "composite"
  steps:
    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: "18"

    - name: Running index.js
      run: ${{ github.workspace }}/.github/actions/run-code/run-code.sh << EOF
${{ inputs.files }}
EOF
      shell: bash
