name: Building
description: Building
inputs:
  working-directory:
    description: Path where build should be done
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Downloading dependencies
      run: |
        npm i
      working-directory: ${{ inputs.working-directory }}

    - name: Building
      run: |
        npm run compile
      working-directory: ${{ inputs.working-directory }}
