name: Build and run script
on: push
jobs:
  build:
    environment: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/is-changed
        id: is-changed
        with:
          dir: "."
      - name: Print
        run: echo ${{ steps.is-changed.outputs.any_changed }}

      # - name: Build
      #   uses: ./.github/actions/build-code
      #   with:
      #     work-dir: "."
      #
      # - name: Run
      #   uses: ./.github/actions/run-code
      #   with:
      #     work-dir: "./build"
      #     name: "Vardan,Test"

      # - name: Test
      #   run: |
      #     echo ${{ vars.TEST }}
      #     echo ${{ github.base_ref }}
      #     echo ${{ github.ref }}
      #     echo ${{ github.ref_name }}
      #     echo ${{ github.env }}
