name: Build and run script
on: push
jobs:
  build:
    environment: ${{ github.GITHUB_BASE_REF }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Build
      #   uses: ./.github/actions/build-code
      #   with:
      #     work-dir: "."
      #
      # - name: Run
      #   uses: ./.github/actions/run-code
      #   with:
      #     work-dir: "./build"
      #     name: "Vardan,Test"

      - name: Test
        run: |
          echo ${{ vars.TEST }}
