name: Build and run script
on: push
env:
  TEST_VAR2: VAR2 test
jobs:
  # aaa:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: test
  #       id: test
  #       run: echo "name=[\"Vardan\"]" >> $GITHUB_OUTPUT
  #   outputs:
  #     names: ${{ steps.test.outputs.name }}
  #
  # build:
  #   needs: [aaa]
  #   runs-on: ubuntu-latest
  #   if: needs.aaa.outputs.names == '[]'
  #   strategy:
  #     matrix:
  #       name: ${{ fromJSON(needs.aaa.outputs.names) }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Print name
  #       run: echo ${{ matrix.name }}
  #   outputs:
  #     name: ${{ matrix.name }}
  #
  test:
  #   needs: [build, aaa]
  #   # if: needs.aaa.outputs.names != '[]'
    runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       name: ${{ fromJSON(needs.aaa.outputs.names) }}
  #   steps:
  #     - name: Test
  #       run: echo ${{ matrix.name }}

      # - name: Test
      #   run: echo ${{ env.${{github.ref_name}} }}

      # - uses: ./.github/actions/is-changed
      #   id: is-changed
      #   with:
      #     dir: "./src"
      # - name: Print
      #   run: echo ${{ steps.is-changed.outputs.any_changed }}

      # - name: Build
      #   uses: ./.github/actions/build-code
      #   with:
      #     work-dir: "."
      #
      # - name: Upload archives into artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: lambda-functions-archives
      #     path: ${{ github.workspace }}/build/
      # - name: Create test directory
      #   run: mkdir test
      # - name: Download archives from artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: lambda-functions-archives
      #     path: test
      # - name: list
      #   run: ls -ls
      # - name: list2
      #   run: cd test && ls -ls

      - name: Run
        env:
          TEST_VAR: Hello
        uses: ./.github/actions/run-code

      # - name: Print name
      #   run: echo ${{ steps.test.outputs.aaa }}

      # - name: Test
      #   run: |
      #     echo ${{ vars.TEST }}
      #     echo ${{ github.base_ref }}
      #     echo ${{ github.ref }}
      #     echo ${{ github.ref_name }}
      #     echo ${{ github.env }}
