name: Build and run script
on: push
jobs:
  # aaa:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: test
  #       id: test
  #       run: echo "name=[\"Vardan\"]" >> $GITHUB_OUTPUT
  #   outputs:
  #     names: ${{ steps.test.outputs.name }}
  #
  # build:
  #   needs: [aaa]
  #   runs-on: ubuntu-latest
  #   if: needs.aaa.outputs.names == '[]'
  #   strategy:
  #     matrix:
  #       name: ${{ fromJSON(needs.aaa.outputs.names) }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Print name
  #       run: echo ${{ matrix.name }}
  #   outputs:
  #     name: ${{ matrix.name }}
  #
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run
        uses: ./.github/actions/run-code
        with:
          files:
            - src/index.ts
            - src/test.ts
