name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@4

      - name: Build
        uses: ./.github/actions/build
        with:
          working-directory: "."
