name: Build and run script
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ua: dev
      preprod: ua
      prod: preprod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Test
      #   run: echo ${{ env.${{github.ref_name}} }}

      # - uses: ./.github/actions/is-changed
      #   id: is-changed
      #   with:
      #     dir: "./src"
      # - name: Print
      #   run: echo ${{ steps.is-changed.outputs.any_changed }}

      # - name: Build
      #   uses: ./.github/actions/build-code
      #   with:
      #     work-dir: "."
      #
      # - name: Upload archives into artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: lambda-functions-archives
      #     path: ${{ github.workspace }}/build/
      # - name: Create test directory
      #   run: mkdir test
      # - name: Download archives from artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: lambda-functions-archives
      #     path: test
      # - name: list
      #   run: ls -ls
      # - name: list2
      #   run: cd test && ls -ls

      - name: Run
        id: test
        uses: ./.github/actions/run-code

      - name: Print name
        run: echo ${{ steps.test.outputs.aaa }}

      # - name: Test
      #   run: |
      #     echo ${{ vars.TEST }}
      #     echo ${{ github.base_ref }}
      #     echo ${{ github.ref }}
      #     echo ${{ github.ref_name }}
      #     echo ${{ github.env }}
